apiVersion: v1
kind: Secret
metadata:
  name: backendsofa-secrets
type: Opaque

stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/sofa_db"
  JWT_SECRET: "your_jwt_secret"
  NODE_ENV: "development"
  JWT_ACCESS_SECRET: "your-access-secret"
  JWT_REFRESH_SECRET: "your-refresh-secret"
  JWT_ACCESS_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  ADMIN_EMAIL: "admin@example.com"
  ADMIN_PASSWORD: "Admin@12345"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "sofa_db"
